name: MMO

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      
jobs:
  MMOItems:
    uses: HenryDuck/ServerProjects/.github/workflows/maven-build.yml@main
    with:
        repository: "HenryDuck/ServerProjects"
        target: "resources/MMOItems/*"
        name: "MMOItems"
  MMOCore:
    uses: HenryDuck/ServerProjects/.github/workflows/maven-build.yml@main
    with:
        repository: "HenryDuck/ServerProjects"
        target: "resources/MMOCore/*"
        name: "MMOCore"
